#!/bin/sh -e

export PREFIX=""
if [ "$VIRTUAL_ENV" != '' ]; then
    export PREFIX="$VIRTUAL_ENV/bin/"
elif [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

export SOURCE_FILES="{{ cookiecutter.package_name }} tests"
set -x

${PREFIX}mypy {{ cookiecutter.package_name }}
${PREFIX}ruff check $SOURCE_FILES --fix --line-length 99
${PREFIX}black $SOURCE_FILES --line-length 99
