version: 3

tasks:
  # --------------------------- SETUP ------------------------------------

  activate:
    desc: Activates the virtual environment in development mode
    cmds:
      - hatch shell

  clean_ruff:
    desc: "Remove all .ruff_cache directories"
    cmds:
      - |
        find . \
          -type d \
          -name ".ruff_cache" \
          -exec rm -rf {} +

  clean_mypy:
    desc: "Remove all .mypy_cache directories"
    cmds:
      - |
        find . \
          -type d \
          -name ".mypy_cache" \
          -exec rm -rf {} +

  clean_pytest:
    desc: "Remove all .pytest_cache directories"
    cmds:
      - |
        find . \
          -type d \
          -name ".pytest_cache" \
          -exec rm -rf {} +

  clean:
    desc: Cleans caching, pyc and pycache files
    cmds:
      - hatch run clean_pyc
      - hatch run clean_pyi
      - hatch run clean_pycache
      - task clean_ruff
      - task clean_mypy
      - task clean_pytest

  build_with_checks:
    desc: Builds the project with checks
    cmds:
      - hatch run build_with_check

  lint:
    desc: Lints the project
    cmds:
      - hatch run lint

  format:
    desc: Formats the project
    cmds:
      - hatch run format

  mypy:
    desc: Runs the type checker only, no formatting
    cmds:
      - hatch run test:check_types

  #---------------------------- DOCS -------------------------------

  build:
    desc: Builds the documentation
    cmds:
      - hatch run docs:build

  serve:
    desc: Runs the documentation in live mode
    cmds:
      - hatch run docs:serve

  # --------------------------- TEST ------------------------------------

  test:
    desc: Runs the suite tests
    env:
      LILYA_SETTINGS_MODULE: tests.settings.TestSettings
    cmds:
      - hatch run test:test {{ .ARGS }}

  test_man:
    desc: Runs the manual tests with more output details and python breakpoints allowed
    env:
      LILYA_SETTINGS_MODULE: tests.settings.TestSettings
    cmds:
      - hatch run test:test_man {{ .ARGS }}

  coverage:
    desc: Runs the coverage tests
    env:
      LILYA_SETTINGS_MODULE: tests.settings.TestSettings
    cmds:
      - hatch run test:coverage {{ .ARGS }}
